const SET_IS_PROJECT_LIST_FETCHING = 'PROJECTS/IS_PROJECT_LIST_FETCHING';
const SET_PROJECTS = 'PROJECTS/SET_PROJECTS';
const SET_FETCH_PROJECTS_ERROR = 'PROJECTS/SET_FETCH_PROJECTS_ERROR';

export {
  SET_IS_PROJECT_LIST_FETCHING,
  SET_PROJECTS,
  SET_FETCH_PROJECTS_ERROR,
};
