const SET_IS_USER_LIST_FETCHING = 'USERS/IS_USER_LIST_FETCHING';
const SET_USERS = 'USERS/SET_USERS';
const SET_FETCH_USERS_ERROR = 'USERS/SET_FETCH_USERS_ERROR';

const SET_USER_LIST_PAGINATION = 'USERS/SET_USER_LIST_PAGINATION';

export {
  SET_IS_USER_LIST_FETCHING,
  SET_USERS,
  SET_FETCH_USERS_ERROR,

  SET_USER_LIST_PAGINATION,
};
