const SET_IS_USER_PROJECT_LIST_FETCHING = 'USERS_PROJECTS/IS_USER_PROJECT_LIST_FETCHING';
const SET_USERS_PROJECTS = 'USERS_PROJECTS/USERS_PROJECTS';
const SET_FETCH_USERS_PROJECTS_ERROR = 'USERS_PROJECTS/FETCH_USERS_PROJECTS_ERROR';

const ADD_USER_PROJECT = 'USERS_PROJECTS/ADD_USER_PROJECT';
const REMOVE_USER_PROJECT = 'USERS_PROJECTS/REMOVE_USER_PROJECT';

export {
  SET_FETCH_USERS_PROJECTS_ERROR,
  SET_IS_USER_PROJECT_LIST_FETCHING,
  SET_USERS_PROJECTS,

  ADD_USER_PROJECT,
  REMOVE_USER_PROJECT,
};
